### ISSUE TITLE
Stabalize the shorthand Decimal notation

### ISSUE THREAD

**Issue by paupino** [paupino/rust-decimal#11]
Creating a new decimal object is rather verbose. It'd be nice to have a shorthand option to define a decimal such as: `12.4M`. This could possibly be implemented via a `build.rs` file.

**Comment by paupino** [comment]
Using `build.rs` may be a bit pre-emptive since we need to write files for this to work. This could work with an external library using `proc_macro_derive`.

**Comment by paupino** [comment]
This may require

**Comment by paupino** [comment]
This may require some sort of plugin like [`proc_macro_plugin`](http://manishearth.github.io/rust-internals-docs/proc_macro_plugin/index.html).

**Comment by paupino** [comment]
A nightly only implementation has been created which relies on stablilization of [#38356](https://github.com/rust-lang/rust/issues/38356).

There may be an opportunity to leverage [procedural_masquerade](https://docs.rs/procedural-masquerade/0.1.5/procedural_masquerade/) to ensure this works on stable also.

**Comment by gabisurita** [comment]
```
```

**Comment by paupino** [comment]
One small change you could also make to avoid the additional `to_string` is to use `stringify`:

```rust
macro_rules! dec {
    ($e:expr) => {
        {
            use std::str::FromStr;
            Decimal::from_str(stringify!($e)).unwrap()
        }
    };
}
```

Hopefully this feature will be stabalizing soon with Rust 2018!
