### ISSUE TITLE
Doesn't support parsing of Decimals with scientific notation

### ISSUE THREAD

**Issue by andoriyu** [paupino/rust-decimal#110]
I did my own implementation, but I don't think it's pretty and/or perfomant, but I'd like to have support for numbers like "9.7e-7", "1.2e10" etc.

**Comment by andoriyu** [comment]
Something like that:
```rust
    fn from_scientific(value: &str) -> Result<Decimal, Error> {
        let err = Error::new("Failed to parse");
        let mut split = value.splitn(2, 'e');

        let base = split.next().ok_or(err.clone())?;
        let mut scale = split.next().ok_or(err.clone())?.to_string();

        let mut ret = Decimal::from_str(base)?;

        if scale.contains('-') {
            scale.remove(0);
           let scale: u32 = scale.as_str().parse().map_err(move |_| err.clone())?;
           let current_scale = ret.scale();
           ret.set_scale(current_scale+ scale)?;
        } else {
            if scale.contains('+') {
                scale.remove(0);
            }
            let pow: u32 = scale.as_str().parse().map_err(move |_| err.clone())?;
            ret *= Decimal::from_i64(10_i64.pow(pow)).unwrap();
        }
        Ok(ret)
    }
```

**Comment by paupino** [comment]
Thanks for this submission. It is something that I've considered adding, in addition to supporting different radix. I'll have a play and see what I can come up with over the next week. I suspect we can get some nice optimizations here since we essentially store in a scientific format already (i.e. value * 10^scale).

**Comment by paupino** [comment]
Sorry for the delay in getting this one through. I've got a working example on the branch `feature/scientific` however want to see if I can improve the performance further. That being said, since it is likely a low use call I could probably merge it and improve it later on.

**Comment by andoriyu** [comment]
@paupino yeah, even mess I wrote was working fine for my use case.
