### ISSUE TITLE
implement std::ops::Neg for Decimal

### ISSUE THREAD

**Issue by snd** [paupino/rust-decimal#125]
the following code fails to compile:

```rust
let x = dec!(7314);
let y = -x;
```

with error:

```
40 |     let y = -x;
   |             ^^ cannot apply unary operator `-`
   |
   = note: an implementation of `std::ops::Neg` might be missing for `rust_decimal::Decimal`
```

**do you want std::ops::Neg implemented?** then i'd do so and open a PR : )

**Comment by paupino** [comment]
That sounds super useful; thank you!

**Comment by snd** [comment]
just started implementation when i found this already exists. though only on master and not the latest version (`0.8.1`) released on crates. maybe time to release a new version?
