### ISSUE TITLE
change Debug for Decimal to print represented number

### ISSUE THREAD

**Issue by snd** [paupino/rust-decimal#126]
currently `Decimal` derives `Debug` https://github.com/paupino/rust-decimal/blob/756e61370265beb5d04475334907519b06674204/src/decimal.rs#L78

when printing out for a example a vec of some structs containing decimals with `{:?}` or `{:#?}`
in place of the decimals one gets a lot of `Decimal { flags: 131072, hi: 0, lo: 3260, mid: 0 }`
and has to do additional annoying work to print the actual number represented.

implementing `Debug` like `Display` and printing the number represented by the decimal would help me a lot.

**is this something you want?**

would be happy to implement this then!

**Comment by paupino** [comment]
I’ve thought about this one also. Debug is currently useful when I’m debugging the internals - though I still prefer base 8 format. When consuming the library it’s currently a little useless. 
I think it makes sense to change the default Debug impl and reimplement the internal dump through another function.

**Comment by snd** [comment]
would you be willing to merge a PR that simply implements Debug like Display and adds an additional function `debug_internal` (or is there another name you'd prefer) that returns a String that corresponds to what Debug currently does?

**Comment by paupino** [comment]
That sounds great. For the "internal" name perhaps we keep `fmt` in there somewhere. Perhaps even just simply `debug_internal_fmt`?

Ultimately the current debug format is kind of useless as it spits out the data in base10 (base16 would be better) so all in all this is a good change. 

Thank you for your help!
