### ISSUE TITLE
missing panic on overflow !?

### ISSUE THREAD

**Issue by snd** [paupino/rust-decimal#127]
thanks for your work on this crate : ) so far it's been very useful to me.

i've replaced some code that previously used `f64`s by `Decimal`s.
the code did some plotting in the end.
when comparing the plots i noticed a lot of differences.
i was able to reduce it to a minimal example:

```rust
    let mut x = dec!(7314.6229858868828353570724702);
    let y = dec!(1000);
    x += y;
    println!("{}", x);
```

prints:
```
391.8067344604490760026774366
```

this seems pretty bad to me : /

i guess it's an overflow. **i think it should absolutely panic in this case instead of silently breaking math!**

using rust decimal `0.8.1` and `rustc 1.27.0-nightly (f0fdaba04 2018-05-15)`

**Comment by paupino** [comment]
Agreed. Will look into this one. Thanks for the example!

**Comment by paupino** [comment]
So there is definitely an overflow happening with addition whereby the last bit exceeds the allocated 96 bit storage space _at that scale_. While I could overflow, I feel like this should rather work and instead round to `8314.622985886882835357072470`. 

If I did this and instead provided [checked functions](https://github.com/paupino/rust-decimal/issues/80) would this help your case?

**Comment by snd** [comment]
rounding the last decimal places and loosing a tiny bit of precision sounds like a good solution for cases like this.

i can imagine there are users that don't want to silently loose even a tiny bit of precision and would like to know when overflow/rounding occurs. the checked functions sound like a good solution.

**how do we ensure that there are no further cases like this, where an overflow silently results in completely wrong results?** you describe the crate as `suitable for financial calculations`. in financial applications errors like this could have pretty bad consequences.

i'd have more confidence in the crate if it tested common math invariants using something like https://github.com/BurntSushi/quickcheck. happy to add some quickcheck tests if you agree.

**Comment by paupino** [comment]
QuickCheck looks interesting - I'd be happy to get this included. How would you intend on utilizing it?

**Comment by paupino** [comment]
I'm going to pull implementing QuickCheck into a new issue so I can close this one once it's fixed.
