### ISSUE TITLE
i128/u128 based implementation

### ISSUE THREAD

**Issue by xilec** [paupino/rust-decimal#135]
My small experiments shows that implementation `Decimal` on top of types `i128`/`u128` should be simpler and more performant. In my rough reimplementation of `add` method, timings of bench `add_negative_pi` drops from 133 ns/iter to 41 ns/iter. As I know, `i128`/`u128` types supported on all rust targets. 
I suppose it enough reasons to consider reimplementation or alternative implementation of `Decimal` type on top of `i128`/`u128`.

**Comment by paupino** [comment]
This is still on the roadmap however due to significant restructuring will be a V2 feature instead. First stage is to stabalize towards 1.0.

**Comment by vorot93** [comment]
Also this could help expand precision to 128 (or even 256) bits to completely cover theoretical limits of various cryptocurrency values.

**Comment by paupino** [comment]
I've started some experimentation of this in the `evolution` branch. There is much more that needs to be done here, but am open to suggestions. I'm quite curious regarding the crypto scenario and the precision that may be needed here. What sort of precision is typically expected here? (I'm unfamiliar with the implementation of this domain).

**Comment by paupino** [comment]
For those that are following this issue; I'm interested if anyone has found performance _improvements_ on their machine? In my investigations, `i128` and `u128` have been slower. 

I also think there are perhaps three motivations here:
1. Increase storage capacity by using unused bytes
2. Increase storage capacity greater than 128 bits
3. Improve performance by utilizing native `u128`/`i128` types

I've been focusing on number 3 with this (unsuccessfully so far on my hardware), however I suspect others may be looking for either 1 (similar to the C implementation) or perhaps number 2. I'd be interested in any input here to see what people are thinking about.

**Comment by leeson1995** [comment]
@xilec  I wish to refer to your i128 based implementation，thanks a lot ，Can you share a github gist link，thanks a lot ❗️

**Comment by Tony-Samuels** [comment]
It sounds like this has been tried and probably isn't of use right now. Given the lower performance and the other reasons being a change in scale which I think would likely happen under possible generics work in future.

Closing this for now.
