### ISSUE TITLE
Add support for additional rounding strategies

### ISSUE THREAD

**Issue by AndrewSpeed** [paupino/rust-decimal#140]
Hi, first of all thanks for the library,I just started using it and the API is excellent, really easy to get started with :slightly_smiling_face: 

For my use case, I need to make use of the round half up rounding strategy, I was wondering if you were open to adding the ability to either:
 - use more than banker's rounding
 - provide a function that acts as the rounding strategy

I'm more than willing to attempt implementing this, I just wanted to see if it was something you were open to adding into the crate?

**Comment by paupino** [comment]
Thanks! Multiple rounding strategies _has_ been on the list of things to do but unfortunately I see that no issue to track it has been opened. It would be nice to provide at the very least "away from zero" and "towards zero" as options.

I'm certainly open to accepting contributions for adding further rounding options to the library - any help is very much appreciated!

**Comment by AndrewSpeed** [comment]
:+1: I'll start this weekend and get a PR up early to get your feedback, thanks for the fast response
