### ISSUE TITLE
Add an option to Display all Decimal values in floating point notation

### ISSUE THREAD

**Issue by jjpe** [paupino/rust-decimal#153]
Currently, when a `Decimal` is exactly equal to an integer (i.e. `decimal.floor() == decimal`), it is printed without the `.0`. 
For example, the Decimal value `42.0` is represented as `42` rather than `42.0`. This is not consistent with the treatment of the other Decimal values, e.g. `42.3`, which is represented as expected.

I can imagine situations in which this property is useful, but there are also situations which it is more of a hindrance.
For example, in my own code now I have to do this:

```rust
impl fmt::Display for Double {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        match self {
            // This hack is now necessary:
            Double::Decimal(d) if &d.floor() == d => write!(f, "{}.0", d), 
            // regular cases:
            Double::Decimal(d) => write!(f, "{}", d),
            Double::NaN => write!(f, "NaN"),
        }
    }
}
```

**Comment by xilec** [comment]
From C#/.net experience I suppose, the default formatting method should be the most simplest like current variant. And additional formatting methods should be implemented as separate functions (like in [chrono::DateTime](https://docs.rs/chrono/*/chrono/struct.DateTime.html#method.to_rfc2822))
In C# it looks like [this](https://dotnetfiddle.net/Djptie)

**Comment by paupino** [comment]
I'm not sure I quite understand what you're experiencing at the moment. At the moment `42` and `42.0` are represented two different ways (i.e. `42` scale `0` and `420` scale `1`). As an example, both of these tests pass:

```rust
#[test]
fn it_formats_int() {
    let a = Decimal::from_str("5").unwrap();
    assert_eq!(a.to_string(), "5");
    assert_eq!(format!("{}", a), "5");
    assert_eq!(format!("{:.9}", a), "5.000000000");
    assert_eq!(format!("{:.0}", a), "5");
    assert_eq!(format!("{:.2}", a), "5.00");
    assert_eq!(format!("{:010.2}", a), "0000005.00");
    assert_eq!(format!("{:0<10.2}", a), "5.00000000");
}
#[test]
fn it_formats_int_with_precision() {
    let a = Decimal::from_str("5.0").unwrap();
    assert_eq!(a.to_string(), "5.0");
    assert_eq!(format!("{}", a), "5.0");
    assert_eq!(format!("{:.9}", a), "5.000000000");
    assert_eq!(format!("{:.0}", a), "5");
    assert_eq!(format!("{:.2}", a), "5.00");
    assert_eq!(format!("{:010.2}", a), "0000005.00");
    assert_eq!(format!("{:0<10.2}", a), "5.00000000");
}
```

Is there something that you were expecting to be handled differently?

**Comment by paupino** [comment]
Closing, however please reopen if I'm considering things wrong.
