### ISSUE TITLE
Modulo operation returns incorrect result for non-integer values

### ISSUE THREAD

**Issue by 0e4ef622** [paupino/rust-decimal#179]
Example:
```rust
let a: Decimal = "42.2".parse().unwrap();
let b: Decimal = "11.9".parse().unwrap();
println!("{}", a % b);
```
prints `65` instead of `6.5`.

The problem seems pretty obvious, so I looked in the code and saw the comment `Remainder has no scale...`, what's the logic behind that?

**Comment by paupino** [comment]
Hmm, not sure why the comment or logic is there. Like you say, fortunately it should be an easy one to fix.
