### ISSUE TITLE
Atomic Decimal

### ISSUE THREAD

**Issue by NN-Binary** [paupino/rust-decimal#188]
Hi!

Thanks for the crate, sorry not really an issue.
Is there anyway I can do https://doc.rust-lang.org/std/sync/atomic/ with Rust Decimal?

I'm trying but I can't reach anything really working please guys it would be awesome if you give me a working example.

i'm concurrently doing additions (about 500,000 per second) from multiple threads

**Comment by paupino** [comment]
Great question! I'm currently traveling but will see if I can get something going for you over the next few days.

**Comment by HandleMaser** [comment]
awesome thanks :)
ps: i'm 100% sure it would help a ton of people

**Comment by pakipaki2000** [comment]
Highly waiting for this feature too!

**Comment by NN-Binary** [comment]
Any news about it @paupino ? :)

**Comment by paupino** [comment]
Sorry for the delay - I still need to review this deeper to see what may be required. So far I've performed a _quick_ review of `atomic.rs` and believe that we could potentially implement this as a feature mod to essentially wrap `Decimal` within an `UnsafeCell` and expose some basic features. That being said, I need to deeper dive into things like `atomic_compare_exchange` (as an example) and how that may work in this model.

Out of curiosity, I'm assuming `AtomicPtr` isn't suitable?

**Comment by Tony-Samuels** [comment]
I don't think this is possible in stable without going through `AtomicPtr`. Given that an nod response in a fair while, closing this for now. It can be reopened if there's still interest.

**Comment by shirotech** [comment]
Hi @paupino @Tony-Samuels  I have managed to do this atomic operations efficiently, and involves a few simple steps.

1. transmute Decimal into u128, since they can fit all the data exactly.
2. use AtomicU128 from `portable-atomic`
3. transmute back to Decimal on load and vice-versa on store
