### ISSUE TITLE
Example of Bincode

### ISSUE THREAD

**Issue by pakipaki2000** [paupino/rust-decimal#192]
Hi,

```
#[derive(Serialize, Deserialize, PartialEq, Derivative, Clone, Debug)]
#[derivative(Hash, Eq)]

pub struct Input {
    pub client_invoice: [u64; 4],
    pub amount: Decimal
}

```

I really can't make Deserizalization work (bincode), anyway you can provide me a working example for my exact Struct? would be amazing :(

Thank you

**Comment by lnicola** [comment]
See https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=30715b31798f2b2217bdc4273e293242.
