### ISSUE TITLE
Decimal to String

### ISSUE THREAD

**Issue by NN-Binary** [paupino/rust-decimal#193]
Hi,

Is there any safe way that you provide to convert a Decimal to a String? And reach the exact same output?

**Comment by paupino** [comment]
To clarify, are you meaning outside the `fmt` method? https://github.com/paupino/rust-decimal/blob/master/src/decimal.rs#L2329
While `div_by_u32` can panic, it shouldn't. I'm assuming you're looking for further verifications?

**Comment by paupino** [comment]
Closing for now, but please reopen if you need any further information/context.
