### ISSUE TITLE
Consider to move the crait in `rust_num`

### ISSUE THREAD

**Issue by XVilka** [paupino/rust-decimal#197]
Since the decimal arithmetic is crucial for business and financial applications, it makes sense to improve the visibility and make it more abstract (i.e. split from Postgres feature), and move into https://github.com/rust-num organization

cc @rust-num

**Comment by paupino** [comment]
Closing this issue. While it is a good idea, I agree with the @rust-num contributors that it should be a community choice as to which decimal number library they choose. As this develops, this stance may change however for the meantime am closing as there is no action necessary.
