### ISSUE TITLE
Explanation on storage strategy

### ISSUE THREAD

**Issue by devashishdxt** [paupino/rust-decimal#199]
I was going through the code and wanted to understand if there is any particular reason to store the value of `e` and `sign` of decimal value in `flags: u32` instead of having different struct members for both of them (like in `UnpackedDecimal`)?

**Comment by paupino** [comment]
The original idea is to ensure that this remains as 128 bits of ultimately 4 words (32bit arch). This allows us to potentially align in memory and achieve some optimizations by doing so. Admittedly, it was also inspired by Microsoft's Decimal number type even to this day.
