### ISSUE TITLE
Signed zeros are not equal, is this intended?

### ISSUE THREAD

**Issue by hengchu** [paupino/rust-decimal#209]
```
#[test]
fn test_decimal_behavior() {
    let zero: Decimal = 0.into();

    assert!(zero == zero);
    assert!(-zero == zero);
    assert!(zero == -zero);
}
```

The second and third `assert` would fail. Is this the intended behavior of the `Decimal`?

**Comment by paupino** [comment]
Not intended. I'll issue a fix for master, but will wait for a couple of extra changes to make it in before issuing a minor release.

**Comment by hengchu** [comment]
Thanks for the quick response and patch!
