### ISSUE TITLE
Rust `num` trait implementations

### ISSUE THREAD

**Issue by tspooner** [paupino/rust-decimal#224]
Hey @paupino,

First of all, thanks for the crate - some incredibly useful stuff here for a project I'm currently working on in fintech. The problem I'm having at the moment is that my code is generic over many of the traits defined in `num`. I appreciate that you have already integrated with casting and `Zero`/`One`, but I need to be able to assert that the given type implements `Signed` and `Num`.

I realise that I could use the newtype pattern etc, but this adds a huge amount of maintenance to the codebase, and I would much rather people be able to work directly with your type.

Do you have any plans to implement these traits in particular (I noticed you mention the `Pow` trait in other issues)? If not I'd be more than happy to take a stab and implementing at least a subset of them and sending a PR.

In case this is already something you've considered/discussed - apologies.

Thanks again,
Tom

**Comment by paupino** [comment]
I think this is a good idea. I'd also like to remove the "meta crate" dependency and only focus on `num_traits`. I may look at doing that all in one PR.

**Comment by tspooner** [comment]
Excellent. No rush, but if you want anyone to help/contribute just let me know.

Cheers,
Tom

**Comment by paupino** [comment]
@tspooner I've put up a PR (#225) which implements `Num` and `Signed`. Does this cover your needs?

**Comment by tspooner** [comment]
Excellent - yes that covers everything I need! Cheers for implementing so quickly!
