### ISSUE TITLE
Possible loss of precision/wrong result on conversion from f64

### ISSUE THREAD

**Issue by tomhoule** [paupino/rust-decimal#228]
For `0.00006927f64`, `Decimal::from_str(&f.to_string())` works fine, but `Decimal::from_f64(f)` will return `0.00006927000000000001`.

I committed a test case with the failing value here: https://github.com/tomhoule/rust-decimal/commit/df6196c7c9cf802c0c4e6fcb680c4275fd3b7acb

Please tell me if I can help any further :)

**Comment by paupino** [comment]
That's for raising this - fortunately, I can reproduce this quite easily. I'll see if I can trace down the root cause.
