### ISSUE TITLE
Optimizing to_f64?

### ISSUE THREAD

**Issue by hengchu** [paupino/rust-decimal#234]
First of all, I want to thank you for this wonderful package!

I have an data-intensive application that utilizes `rust-decimal`, and calls `to_f64()` a lot. A recent instrumentation showed me that my application is spending roughly 10% of the time in `to_f64()` due to the current conversion algorithm (https://github.com/paupino/rust-decimal/blob/ba5ba1f661bf67a8e12bba8c9fdc438d69371e69/src/decimal.rs#L2526-L2541), which essentially converts `Decimal` to `f64` through an intermediate string.

The current implementation has a TODO that suggests there may be a faster way of doing this conversion. I'd love to help with this optimization. Do you have some pointers on how to get started? Would the mantissa algorithm be something like the inverse of `Decimal::base2_to_decimal`?

**Comment by paupino** [comment]
Ah yes! That wouldn't be very performant at all.

Essentially, we'd want to be able to reconstruct the raw float again similar to how it's deconstructed here: 
https://github.com/paupino/rust-decimal/blob/master/src/decimal.rs#L2457-L2460

To do this, we'd need to recalculate the parts of the formula: `n = (sign*-1) * 2^exp * mantissa`
Sign is easy - the tricky parts are firstly calculating the `exponent2` and the `mantissa`. I  think you could do this in a very similar way (except, the inverse) to how it's been leveraged within this function.

I'm more than happy to pick it up also, but am more than grateful to get some help for maintenance - so thank you!

**Comment by paupino** [comment]
Closed with #235
