### ISSUE TITLE
Incorrect behavior in from_str_radix

### ISSUE THREAD

**Issue by 0e4ef622** [paupino/rust-decimal#242]
```rust
use rust_decimal::prelude::*;
use num_traits::Num;

fn main() {
    // 32 ones
    println!("{:?}", Decimal::from_str_radix("11111111111111111111111111111111", 2));
}
```
Expected output: `Ok(4294967295)`
Actual output: `Ok(536870912)`

The binary representation of the actual output is:
`100000000000000000000000000000`
That's 1 one followed by 29 zeroes.

**Comment by paupino** [comment]
It appears this is triggering rounding - which of course, is absolutely incorrect. I can put in a simple fix, however I want to make sure this transitions across different bases.

**Comment by paupino** [comment]
I think this is actually due to this logic:
```
if coeff.len() as u32 > MAX_PRECISION {
    maybe_round = true;
    break;
}
```
This works well when the base is `10+` as it's safe to exit out early. However this is a very naive exit when it's less than base `10`.
