### ISSUE TITLE
Documentation for is_sign_positive/negative seem ambiguous?

### ISSUE THREAD

**Issue by hengchu** [paupino/rust-decimal#250]
The function names `is_sign_positive` and `is_sign_negative` suggests that these functions only test the sign bit. But the documentation suggests otherwise:
https://github.com/paupino/rust-decimal/blob/9f9797b33572292404af527ed5891d146d3a9e06/src/decimal.rs#L474-L484

Testing the actual behavior suggests the function names are accurate, while the documentation should be changed (since typically I would assume `0` is neither positive nor negative...):
```rust
    #[test]
    fn decimal_behavior() {
        let mut a: Decimal = 1.into();
        a -= Decimal::from_i64(1).unwrap();
        assert_eq!(a, 0.into());
        assert!(! a.is_sign_positive()); // fails here, because a's sign bit is indeed positive
        assert!(! a.is_sign_negative());
    }
```

Just wanted to confirm that this is indeed the intended behavior. If so, I can submit a PR for the documentation update.

**Comment by paupino** [comment]
Hi @hengchu - yes, the intention is for it to just check the sign bit. Most of the time this is fairly binary, except for the zero case of course whereby both `-0` and `+0` can be represented.  Would you recommend changing the documentation to specify the "sign bit"? e.g. "Returns `true` if the sign bit of the decimal is negative. "

**Comment by hengchu** [comment]
> Hi @hengchu - yes, the intention is for it to just check the sign bit. Most of the time this is fairly binary, except for the zero case of course whereby both `-0` and `+0` can be represented. Would you recommend changing the documentation to specify the "sign bit"? e.g. "Returns `true` if the sign bit of the decimal is negative. "

Yeah I think that would better align with the purpose of these functions and their names.

On top of that, it might make sense to also provide functions `is_positive/negative` that actually tests the numerical positive/negative property. What do you think?

(I know there currently exist deprecated functions with these names that test the sign bit instead, I guess we could give these functions other names...)
