### ISSUE TITLE
Consider using bitvec or bitflags to represent Decimal fields

### ISSUE THREAD

**Issue by KiChjang** [paupino/rust-decimal#262]
Per title. The main benefit I see here is that we don't need to manually bit shift and mask ourselves; instead, we can just use the rich API provided by bitvec. In addition, it has some really nice APIs such as the ability to loop through each bit individually. I can imagine that this will come in handy for some algorithms that this crate is currently using or will be using in the future.

**Comment by paupino** [comment]
Closing this issue for now as it's not something that is really required as of yet (i.e. it'd be adding another dependency for not clear benefit). It is something, however, I'll keep in mind as we move towards #335 as the fundamental approach for this is leveraging binary overflow properties to get intrinsic speed improvements.
