### ISSUE TITLE
Add inline to all from methods for improving speed.

### ISSUE THREAD

**Issue by heckad** [paupino/rust-decimal#266]
Benchmark:
```
#![feature(test)]
extern crate test;

pub use decimal::Decimal;

#[bench]
fn recycled_cycling(b: &mut test::Bencher) {
    b.iter(|| {
        Decimal::from(2) > 0.into()
    })
}
```
On my machine, this takes `15 ns/iter`. After adding `#[inline]`, this takes `3 ns/iter`

**Comment by paupino** [comment]
I'm not sure I quite understand this issue. Currently `from` is inlined as per this code: https://github.com/paupino/rust-decimal/blob/2b900e827853039c18b24cbeb9cfa16229574781/src/decimal.rs#L3161-L3185

Is there another function you're referring to? Perhaps inlining `FromPrimitive`?

**Comment by paupino** [comment]
Closing for now due to inactivity. I'll continue to keep an eye on inlining where possible.
