### ISSUE TITLE
feature request: method to print decimal as scientific notation

### ISSUE THREAD

**Issue by orbli** [paupino/rust-decimal#271]
as title.

i hope there is a function to print the decimal as a string of scientific notation like `"1e-5"` from 0.00001.

**Comment by paupino** [comment]
This should be relatively straight forward to implement. For the meantime, if you wanted to reproduce it you could have a function like:

```rust
fn to_scientific(num: &Decimal) -> String {
    format!("{}e{}{}", num.trunc(), if num.is_sign_negative() { "-" } else { "" }, num.scale())
}
```

I'll look at getting an optimized version into the next minor release.
