### ISSUE TITLE
Missing tags

### ISSUE THREAD

**Issue by pfrenssen** [paupino/rust-decimal#273]
I see on [crates.io](https://crates.io/crates/rust_decimal/versions) that there are versions 1.7.0 and 1.8.0 for rust_decimal, but these tags are missing from the releases: https://github.com/paupino/rust-decimal/releases

The last tag shown is 1.6.0.

**Comment by paupino** [comment]
My fault - sorry about that. I'll likely introduce a Makefile to help ensure these happen as part of publish going forward. The simple truth is that I forgot to push up the tag after publish. I do know when I cut off 1.7.0 so could add it in retrospect, however would rather try to ensure tagging happens upon publish going forward.
