### ISSUE TITLE
Division prohibitively slow

### ISSUE THREAD

**Issue by smessmer** [paupino/rust-decimal#276]
Thank you very much for this great project, the accuracy offered by this over f64 is very helpful to me.

I'm using rust-decimal 1.8.1.

Unfortunately, it turned out that I cannot use the division operator for decimals because it is prohibitively expensive. Is there a way to optimize it and get closer to the performance of multiplication?

**Benchmark:**
```
$ cargo run --release
    Finished release [optimized] target(s) in 0.01s
     Running `target/release/mytest`
rust-decimal division : 9388.19 ns
rust-decimal multiplication : 36.4715 ns
f64 division : 1.2322 ns
f64 multiplication : 1.4745 ns
```

That the operations on decimal are slower than the operations on f64 is expected and a slowdown factor of around 40x for multiplication is acceptable. The slowdown factor of around 10.000x for division is unfortunately prohibitive for my use case, calls to decimal division were very dominant in my performance profile.

**Benchmark code:**
```rust
use rust_decimal_macros::dec;
use std::time::Instant;

fn bench<T: std::fmt::Debug + Copy + std::ops::AddAssign<T>>(name: &'static str, a: T, b: T, s: T, f: impl Fn(T, T) -> T) {
  const NUM_ITERATIONS: u128 = 10000;

  // warmup
  let mut s = s;
  for _ in 0..=100 {
    s += f(a, b);
  }

  // bench
  let start = Instant::now();
  for _ in 0..NUM_ITERATIONS {
    s += f(a, b);
  }

  // print the dummy value so that the compiler can't optimize our computations away
  println!("dummy: {:?}", s);

  println!("{} : {} ns", name, start.elapsed().as_nanos() as f64 / NUM_ITERATIONS as f64);
}

fn main() {
  bench("rust-decimal division", dec!(1.02343545345), dec!(0.35454343453), dec!(0.0), |a, b| a / b);
  bench("rust-decimal multiplication", dec!(1.02343545345), dec!(0.35454343453), dec!(0.0), |a, b| a * b);
  bench("f64 division", 1.02343545345_f64, 0.35454343453_f64, 0.0_f64, |a, b| a / b);
  bench("f64 multiplication", 1.02343545345_f64, 0.35454343453_f64, 0.0_f64, |a, b| a * b);
}
```

**Comment by paupino** [comment]
Division has been one of those areas in this which I know I definitely needed to revisit at some stage. At the moment it is using twos-complement division with some minor binary "fixed size type" optimizations, however I would like to explore some other algorithms to see where there is opportunity for more evenly distributed performance improvements (i.e. the more complex the result, the longer it takes).

I'm happy to take a look at it again, perhaps even trialing out some alternative algorithms using feature flags before stabilizing. I'll keep this ticket open and track progress here. Of course, if there is anyone in the community that wants to help with this then the more the merrier!

**Comment by smessmer** [comment]
I confirmed the benchmarks improved significantly. Measured on a different machine as above.

Version 1.9:
```
rust-decimal division : 10842.1662 ns
rust-decimal multiplication : 24.4317 ns
f64 division : 1.2197 ns
f64 multiplication : 1.3686 ns
```
current master:
```
rust-decimal division : 111.8301 ns
rust-decimal multiplication : 26.6219 ns
f64 division : 1.3238 ns
f64 multiplication : 1.6402 ns
```

Not as fast as multiplication yet, but much much (~ 100x) better than before. Thank you very much. Now I just need a release containing this fix :)
