### ISSUE TITLE
Small Decimal64

### ISSUE THREAD

**Issue by zeroflaw** [paupino/rust-decimal#277]
I work mostly with small monetary values, which would all fit within a single u64 value. Would you accept a pull request that exposes a "Decima64" or "DecimalSmall" that uses only one u64 instead of 3 u32? My thinking this would improve performance when dealing with values such as these.

**Comment by aldanor** [comment]
@zeroflaw Why did you close it?

I was actually looking for the same thing, wondering if you found any alternative or other solution?

**Comment by zeroflaw** [comment]
After doing some experiments I realised it would make more sense to package into its own crate. Providing conversion methods between "small decimal" and "big decimal (rust_decimal). If @paupino wanted to merge them together I would be happy with that.

The thing is a u64 for a decimal really isn't a lot of precision, and while my use case benefits a lot from a single u64 representation. I feel that most people would want to use rust_decimal. 

I haven't fully tested the "small decimal" code yet, but if you are interested I'll post back here when its on crates.io

**Comment by quantverse** [comment]
Great idea, I also need smaller version of Decimal for monetary values. Separate crate makes sense too. Please post back when released, thanks!
