### ISSUE TITLE
Compatibility with serde_json's `arbitrary_precision` feature flag

### ISSUE THREAD

**Issue by rkusa** [paupino/rust-decimal#283]
`serde_json` has a `arbitrary_precision` feature flag, which is described as:

```rust
# Use an arbitrary precision number representation for serde_json::Number. This
# allows JSON numbers of arbitrary size/precision to be read into a Number and
# written back to a JSON string without loss of precision.
#
# Unlike float_roundtrip, this feature makes JSON -> serde_json::Number -> JSON
# produce output identical to the input.
```

I might be wrong, but I understand it like:

- JSON does not care about number precision
- `serde_json` usually (if `arbitrary_precision` is not enabled) deserializes numbers with a decimal point as `f64`, so potentially looses precision

This sounds to me like the `arbitrary_precision` feature and `rust_decimal` would be a good fit together. However, `rust_decimal` is currently unable to deserialize a JSON number once `arbitrary_precision` is enabled.

With the feature enabled, the following snippet will fail:

```rust
let d: Decimal = serde_json::from_str("1.1234127836128763").unwrap();
```

I've prepared a repo to reproduce the issue: https://github.com/rkusa/decimal-arbitrary-precision-json

If you run the test there (`cargo test`), it will fail with:

```
invalid type: map, expected a Decimal type representing a fixed-point number
```

What do you think, is it maybe worth investigating here?

---

I've just noticed that I am using your library for almost exactly three years now. It served and still serves me very well, so I cannot thank you enough for making it available and maintaining it 🙏

**Comment by paupino** [comment]
Great writeup, and thank you for the example (and the kind words). I'll need to do some diving into this a bit more; I will look over the next couple of weeks as I start preparing for the next release. It does seem like a good feature to be able to support with Rust Decimal.
