### ISSUE TITLE
no_std is broken by use of f64::powf

### ISSUE THREAD

**Issue by Anders429** [paupino/rust-decimal#286]
The use of `f64::powf` in the `to_f64` method is causing the crate to not build without `std`. Attempting to build without the `std` feature gives the following error: 

```
error[E0599]: no method named `powf` found for type `f64` in the current scope
    --> [...]\.cargo\registry\src\github.com-1ecc6299db9ec823\rust_decimal-1.8.1\src\decimal.rs:2666:34
     |
2666 |             let round_to = 10f64.powf(self.scale() as f64);
     |                                  ^^^^ method not found in `f64`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0599`.
error: could not compile `rust_decimal`
```

It appears that the offending method call [here](https://github.com/paupino/rust-decimal/blob/af0d700a4aab8d2d8083a3fcf1604d8dbe7a7de9/src/decimal.rs#L2666) needs to be changed. I can open a pull request and attempt to address this :)

**Comment by paupino** [comment]
Cool; good catch and thanks for the fix. I can see the problem in the CI so I'll fix that at the same time.

**Comment by paupino** [comment]
Removed `--workspace` test usage for `no_std` which was causing `no_std` tests to not run correctly.
