### ISSUE TITLE
version bump

### ISSUE THREAD

**Issue by cdumontet** [paupino/rust-decimal#308]
Thanks for the great library!

We've been pointing at a GitHub commit.

Given https://github.com/paupino/rust-decimal/pull/302, is there any chance for a version bump?

**Comment by paupino** [comment]
For sure! I was seeing if I could get some add/mul improvements into the release too, however I haven't found as much time to look into those as I'd like. Happy to cut a new release in the meantime - will see if I can push it out this evening.

**Comment by paupino** [comment]
Bumped to `1.10.0`

**Comment by cdumontet** [comment]
Thanks!  Very much appreciated.
