### ISSUE TITLE
Serialize/obtain the unscaled representation

### ISSUE THREAD

**Issue by copumpkin** [paupino/rust-decimal#313]
In financial settings, it's fairly common for the serialized (possibly JSON) form of a message to be scaled by 100. So when I deserialize, I call `rust_decimal::Decimal::new(raw, 2)`. Now I want to round-trip that data for various reasons (test data generation, etc.) so I'd like the inverse of that operation. If I want to extract the `2` I can call `scale()`, but there doesn't seem to be an obvious way to get the unscaled representation back out of the decimal.

Is there a good way to do this today, and if not could one be added?

**Comment by copumpkin** [comment]
The best roundabout way I've been able to find to do this right now has been as follows:

```
let copy = orig;
copy.set_scale(0).expect("scaling");
let raw = copy.to_i128().expect("this can't fail but rust doesn't know that")
```

Which feels a bit messy.

**Comment by paupino** [comment]
This is an interesting case, and certainly something I can extend to support. Fortunately, the method you have above doesn't perform any rescaling so is fairly lightweight, however it shouldn't be too much effort to create an explicit function that doesn't require this workaround at all.
