### ISSUE TITLE
Support re exporting

### ISSUE THREAD

**Issue by Stock84-dev** [paupino/rust-decimal#316]
crate_b re exports as:
```rust
pub use rust_decimal;
pub use rust_decimal_macros;
```
crate_a uses macro:
```rust
use crate_b::rust_decimal::Decimal;
use crate_b::rust_decimal_macros::dec;
let a: Decimal = dec!(1.1);
```
We get: 
```
error[E0433]: failed to resolve: could not find `rust_decimal` in `{{root}}`
```
Is there a reason why we are calling `::rust_decimal::Decimal` ?

**Comment by paupino** [comment]
This is a supported feature in 1.11. It will require, however, that `rust_decimal_macros` is only re-exported with the `reexportable` flag enabled. Some documentation covering this is here: https://github.com/paupino/rust-decimal/blob/4334b15bbeaff85d8aa90556c1238265ad48994d/macros/src/lib.rs#L1-L34
