### ISSUE TITLE
Feature Request: checked_powi

### ISSUE THREAD

**Issue by smessmer** [paupino/rust-decimal#325]
For multiplication, there's a counterpart `checked_mul`, but `powi` just calls the regular multiplication operator and panics on overflows. Would be cool to have a `checked_powi` that doesn't do that.

**Comment by paupino** [comment]
Hi @smessmer, no worries - happy to add this in the next minor release. Please note, `powi` and other mathematical functions will be feature flagged going forward so you'll need to enable the `maths` feature (still unreleased, but will be a requirement for the next version).
