### ISSUE TITLE
A bit more documentation on RoundingStrategy

### ISSUE THREAD

**Issue by rudolphfroger** [paupino/rust-decimal#328]
It was unclear to me how `RoundHalfUp` would work with negative numbers:

```
use rust_decimal::{Decimal, RoundingStrategy};
let d = Decimal::new(-65, 1);
assert_eq!(
    d.round_dp_with_strategy(0, RoundingStrategy::RoundHalfUp),
    Decimal::new(-7, 0)
);
```

This shows -6.5 becomes -7. One could argue that this is a 'round down' since the number became lower, on the other hand the digit 6 went up. In the Python decimal library they've added an explanation: "Round to nearest with ties going away from zero.". I think it would help to add a bit more explanation and maybe examples which show the result of rounding of both positive and negative numbers. I'm happy to write a pull request if you like the idea.

See Python docs on rounding:
https://docs.python.org/3/library/decimal.html#rounding-modes

**Comment by paupino** [comment]
Hi @rudolphfroger - this is great feedback. I agree with the "away from zero" and "towards zero" description. It's feasible that the enum values could be changed also to help with understanding too - albeit a breaking change. In the meantime, I'd certainly welcome a PR contribution if you're up for it.

On a side note, I think the entire set of documentation needs some review to clearly describe potential side effects of operations also. Over the coming months, my goal is to do a sweep of this library to clean things up a bit - perhaps towards a v2. Documentation is potentially an area that I need to address too.

**Comment by rudolphfroger** [comment]
I'll try to make some time to write a pull request in the coming days.

**Comment by paupino** [comment]
I've been doing a bit of cleanup of the library today so hope you don't mind but have cleaned up the documentation/usage a bit. Hopefully it's a bit clearer!

**Comment by rudolphfroger** [comment]
Thanks, I didn't have time yet, so very nice to see this improvement. For me this is a clear explanation.
