### ISSUE TITLE
FromPrimitive i128/u128 typo

### ISSUE THREAD

**Issue by teoxoy** [paupino/rust-decimal#329]
There is a typo in the conversion functions for i128/u128:

https://github.com/paupino/rust-decimal/blob/d96f762f4b14538147db03d6be1b127776ea8173/src/decimal.rs#L2995-L2998

Should be:

- from_i28 -> from_i128
- from_u28 -> from_u128

For reference, here are the functions in question from `num-traits` crate

- [from_i128](https://github.com/rust-num/num-traits/blob/47d69223ce7707ebbf8a91c3e6b3997e48653feb/src/cast.rs#L550)
- [from_u128](https://github.com/rust-num/num-traits/blob/47d69223ce7707ebbf8a91c3e6b3997e48653feb/src/cast.rs#L576)

**Comment by paupino** [comment]
Good catch. Also demonstrates some missing build steps/tests - I'll try to get this addressed sometime this week.

**Comment by paupino** [comment]
The `from_i128`/`from_u128` had quite a few issues however was almost never compiled in to the library due to a misconfiguration. Nonetheless, it should now be working correctly and has surrounding tests to ensure it continues to work.
