### ISSUE TITLE
Feature request: add implementations for CheckedAdd/Sub/Mul/Div/Rem traits from num crate

### ISSUE THREAD

**Issue by teoxoy** [paupino/rust-decimal#330]
I was trying to use num's [`num::range_step_inclusive`](https://docs.rs/num/0.4.0/num/fn.range_step_inclusive.html) and noticed that `CheckedAdd` is not implemented for `Decimal`. `checked_add`, `checked_sub`, `checked_mul`, `checked_div` and `checked_rem` have been added in [v1](https://github.com/paupino/rust-decimal/blob/d96f762f4b14538147db03d6be1b127776ea8173/VERSION.md#100). I think it should be pretty straight forward to implement num's `CheckedAdd`, `CheckedSub`, `CheckedMul`, `CheckedDiv` and `CheckedRem` traits.

**Comment by paupino** [comment]
Should be a fairly trivial change, especially since the `checked` equivalent functions already exist. We'll see what we can do!

**Comment by teoxoy** [comment]
I can put up a PR for this if you want

**Comment by paupino** [comment]
Hi @teoxoy - any help is very much appreciated! Thank you.
