### ISSUE TITLE
exp may panic

### ISSUE THREAD

**Issue by schungx** [paupino/rust-decimal#373]
exp may panic on overflow.

Should there be a `checked_exp`?

**Comment by schungx** [comment]
Currently I cheated out by limiting the exponent <= 10...  ;-)

For small exponents, they trend to zero so it is never an underflow (perhaps it SHOULD be?)

`sqrt` and `ln` also should not overflow as the original number if probably always going to be larger than the result in magnitude...  They probably SHOULD underflow?

**Comment by schungx** [comment]
Since a `Decimal` has a fixed number of bits, it should be easy to calculate the _maximum_ value for `exp`, beyond which it is an overflow.  Then introduce `checked_exp` accordingly.

If we ignore underflows and just allow them to go to zero, then we don't have to introduce checked versions of all others.

**Comment by paupino** [comment]
Closes in #375
