### ISSUE TITLE
Wrong results with exp(-8+)

### ISSUE THREAD

**Issue by schungx** [paupino/rust-decimal#378]
When `exp` with `0.0002` tolerance goes around -8 to -8.5, the result starts flipping into negative.

Which is, of course, incorrect, as there is no index for `exp` that turns out negative.

**Comment by paupino** [comment]
One option here, since it is unlikely to converge, is to return the previous positive result which would be closer? What do you think?

**Comment by schungx** [comment]
Or clamp it down to zero once it flips...  or raise an underflow error...
