### ISSUE TITLE
`attempt to negate with overflow` when using `checked_add`

### ISSUE THREAD

**Issue by c410-f3r** [paupino/rust-decimal#384]
This bug was found by fuzzing tests.

```rust
let a = Decimal::from_parts(0, 67108864, 0, false, 0);
let b = Decimal::from_parts(0, 0, 3873892070, false, 3873892070);
let _c = a.checked_sub(b);
```

**Comment by paupino** [comment]
Hi @c410-f3r - what compile time environment/options did you use when receiving this error? 
I've tried reproducing this however I don't seem to get this error? 
https://github.com/paupino/rust-decimal/pull/new/issues/384

**Comment by c410-f3r** [comment]
Sorry. Just updated the code with an actual falling test
