### ISSUE TITLE
support rounding to significant figures instead of dp

### ISSUE THREAD

**Issue by orbli** [paupino/rust-decimal#389]
as title. i just can't ctrl+F the word "significant" in the doc, probably some operation on exponent in decimal struct would work.

**Comment by paupino** [comment]
Hi @orbli, This is a good suggestion and wouldn't be too hard to implement. It isn't currently available in the API but could be implemented - it _may_ need `log10` support... I'd need to take a look into it. I'll take a look in the next few weeks - unless of course someone wants to grab it before then.
