### ISSUE TITLE
Version 1.14.1 fails to compile

### ISSUE THREAD

**Issue by VladimirGaristov** [paupino/rust-decimal#390]
Hello,
When building a crate that depends on rust-decimal the compiler throws this error:
```
   Compiling rust_decimal v1.14.1
error[E0658]: `if` is not allowed in a `const fn`
   --> /home/cartogan/.cargo/registry/src/github.com-1ecc6299db9ec823/rust_decimal-1.14.1/src/decimal.rs:280:17
    |
280 | /                 if lo == 0 && mid == 0 && hi == 0 {
281 | |                     false
282 | |                 } else {
283 | |                     negative
284 | |                 },
    | |_________________^
    |
    = note: see issue #49146 <https://github.com/rust-lang/rust/issues/49146> for more information
```

The same error appears several more times about different lines in decimal.rs and ops/common.rs.

I'm using InteliJ IDEA Community edition 2021.1.1 #IC-211-7142-45 with the rust plugin version 0.4.147.3871-211 on Arch Linux. rustc version is 1.45.0 (5c1f21c3b 2020-07-13). I'm not actually using rust-decimal myself but I use the mysql crate which depends on rust-decimal.

**Comment by paupino** [comment]
Hi @VladimirGaristov  - I should probably publish the minimum rust version, or at least make it easier to discover. At the moment, the minimum supported rust version is `1.46.0` as described via [this workflow](https://github.com/paupino/rust-decimal/blob/master/.github/workflows/main.yml#L155).

It's certainly a possibility to support lower versions of the compiler via a feature flag. I'd really want to understand what the demand is there first as well as what minimum version is required before going down this path. 

I still need to define the minimum version support policy here - I was hoping to start with a year behind, but perhaps that's not enough? Having a feature flag could help - I just want to make sure I'm not maintaining too many branched versions of code! :)

**Comment by VladimirGaristov** [comment]
Oh, my bad. Turns out I haven't updated my rust toolchain ever since it was installed because I thought pacman does when it updates the rust package. Kinda embarrassing. :D After updating it everything works fine. Thank you for the help.
