### ISSUE TITLE
`log10`

### ISSUE THREAD

**Issue by probablykasper** [paupino/rust-decimal#397]
Currently using [decimal](https://crates.io/crates/decimal), but would love to switch to rust-decimal. The only thing (hopefully) preventing that is log10 support.

For reference, this is decNumber's log10 implementation: https://github.com/gcc-mirror/gcc/blob/16e2427f50c208dfe07d07f18009969502c25dc8/libdecnumber/decNumber.c#L1358-L1523

**Comment by jamesetaylor3** [comment]
If you can put up with an unoptimized solution, you could use the property  `log10(x) =  ln(x) / ln(10)` in the meantime until they implement an native solution. Perhaps this is by design-- I don't know, as I am not affiliated with this project.

```
fn log10(x: Decimal) -> Decimal {
        x.ln() / dec!(10).ln()
}
```

**Comment by probablykasper** [comment]
@jamesetaylor3 Ah cool, had no idea it works like that! Will try that out, thanks

**Comment by paupino** [comment]
Hi both! `log10` hasn't intentionally been left out of the library - it's just that it hasn't been implemented yet.
Some other solutions such as #389 would also benefit from this implementation. Consequently, I'll keep this ticket open as a feature request. We'll see if we can get an implementation of some sort in there within the next minor release or two.
