### ISSUE TITLE
Guidance for a Rust newbie - Decimal constant?

### ISSUE THREAD

**Issue by nwillc-paxos** [paupino/rust-decimal#400]
Given:

```
fn percent_change(prior: Decimal, current: Decimal) -> Decimal {
    (current - prior) / prior * Decimal::from(100)
}
```
Is there a way to have a Decimal::ONE_HUNDRED constant?

**Comment by schungx** [comment]
I would second this, as it is usually quite convenient to have the following constants, in addition to ZERO, ONE, TWO and PI:

NEGATIVE_ONE (useful as a step)
TEN
HUNDRED (useful for percentage calculations), can be simulated via TEN * TEN
THOUSAND (useful for K calculations), can be simulated via TEN * TEN * TEN
E (useful for scientific)

**Comment by c410-f3r** [comment]
It is currently possible to create a constant `Decimal` through the `from_parts` method.
```rust 
const DECIMAL_0_001: Decimal = Decimal::from_parts(1, 0, 0, false, 3);
```
Once https://github.com/rust-lang/rust/issues/51999 is stabilized, it will be possible to write
```rust 
const PI: Decimal = Decimal::try_from_i128_with_scale(3141_i128, 3).unwrap();
```

**Comment by schungx** [comment]
Yes, but in actual usage, it is simpler to just do `Dynamic::TEN` without having to remember to first create the `TEN` const somewhere...
