### ISSUE TITLE
Sin overflowing default stack size

### ISSUE THREAD

**Issue by paupino** [paupino/rust-decimal#419]
Found by @c410-f3r in #418:

https://github.com/paupino/rust-decimal/blob/1e35a73e7650f99abfa2bf0dceb49b41a092239c/src/maths.rs#L536-L542

```rust
#[test]
fn test() {
    use core::str::FromStr;
    let n = crate::Decimal::from_str("-79228162514264.337593543950335").unwrap();
    let _ = n.sin();
}
```

For some reason the above snippet keeps entering the `if self >= &Decimal::PI {` branch in an infinite loop overflowing the default stack size.

**Comment by paupino** [comment]
This is due to recursion trying to scale down the number to fit within `0 <= x <= PI` - by `PI` at a time. This is currently _very_ inefficient for large numbers - and due to the recursive reduction is currently overflowing the stack.

**Comment by c410-f3r** [comment]
Thanks!
