### ISSUE TITLE
Possible typo in documentation around round_dp

### ISSUE THREAD

**Issue by peepopoggers** [paupino/rust-decimal#429]
![image](https://user-images.githubusercontent.com/72892531/135730977-1c0b7f50-1484-4191-a396-bdf404cd37cc.png)

Is it meant to be 7.5 -> 7? Thanks.

**Comment by paupino** [comment]
This is not a typo. With Bankers Rounding it uses Midpoint Nearest Even rules - so the closest even number from 7.5 is 8 hence why it rounds that way (and likewise 6.5 -> 6). 

You can change the strategy that is been used by using 'round_dp_with_strategy'. This gives you more flexibility into which rounding rules should be used.

**Comment by peepopoggers** [comment]
????? why does the first round down and the second round up?

**Comment by paupino** [comment]
Bankers Rounding is common in financial applications when trying to calculate proportions without losing cents from rounding. This gives a bit of an explanation: https://rounding.to/understanding-the-bankers-rounding/

It sounds like you may be looking for: `RoundingStrategy::MidpointTowardZero`. This will round the midpoint towards zero as opposed to using bankers rounding rules (also known as `RoundingStrategy:: MidpointNearestEven`). The full list of differing strategies available can be found [here](https://docs.rs/rust_decimal/1.16.0/rust_decimal/enum.RoundingStrategy.html). Perhaps, like most things, this part of the library could use some better documentation. I'll make a note to look into this when I can.

**Comment by paupino** [comment]
Just to note: the reason this strategy is chosen as the default is really to follow [IEEE-754](https://en.m.wikipedia.org/wiki/IEEE_754#Roundings_to_nearest). We try to follow standards wherever it makes sense whilst still allowing customization wherever possible.

**Comment by schungx** [comment]
> ????? why does the first round down and the second round up? Surely it should be 7.5 -> 7 ?

It is very non-intuitive, but the standard is to round to even numbers.  This way, statistically, if you add up a large column of numbers, there won't be any systematic skew that introduces a large difference.

**Comment by peepopoggers** [comment]
ok I understand now, I did not know it was even numbers only, thanks for clarification.
