### ISSUE TITLE
Use of deserialize_any breaks deserialization with bincode

### ISSUE THREAD

**Issue by jekirl** [paupino/rust-decimal#43]
Currently the `deserialize` implementation calls the serde  `deserialize_any` function, which breaks Decimal serialization with non-self describing formats like bincode [0]. 

> When implementing Deserialize, you should avoid relying on Deserializer::deserialize_any unless you need to be told by the Deserializer what type is in the input. Know that relying on Deserializer::deserialize_any means your data type will be able to deserialize from self-describing formats only, ruling out Bincode and many others.

There are two possible easy fixes:

- Replace `deserialize_any` with `deserialize_str` 
- Simply have Decimal derive `Serialize, Deserialize`

[0] https://serde.rs/impl-deserialize.html

**Comment by paupino** [comment]
Thanks for that write up; I'll take a look into it.

**Comment by paupino** [comment]
Interestingly, simply changing it to `deserialize_str` works for the existing tests. The only type it won't do is:
```
{
  "amount": 100.00
}
```
I'll push in a change for the above now and create a new ticket for float support since it was something that didn't work before.

**Comment by Palmik** [comment]
Hi. Thanks for this crate. The `deserialize_str` was swapped back for `deserialize_any` in [this commit](https://github.com/paupino/rust-decimal/commit/e98415a3ab347d1a5ca0f762463ab16c89bbb5e6) so bincode no longer works by default.

**Comment by paupino** [comment]
I'll look into this a bit some more. I may try and wrap either this or the `any` into a feature so that it gives library consumers the opportunity to select behavior as needed.
