### ISSUE TITLE
Rounding to significant digits doesn't work as expected

### ISSUE THREAD

**Issue by hniksic** [paupino/rust-decimal#430]
Let's say I want to round the number to three significant digits, rounding away from zero:

```rust
fn round3up(d: Decimal) -> Decimal {
    d.round_sf_with_strategy(3, RoundingStrategy::AwayFromZero).unwrap()
}
```

I would expect the following assertions to hold:

```rust
assert_eq!("12400", round3up("12301".parse().unwrap()).to_string());
assert_eq!("124", round3up("123.01".parse().unwrap()).to_string());
assert_eq!("1.24", round3up("1.2301".parse().unwrap()).to_string());
assert_eq!("0.124", round3up("0.12301".parse().unwrap()).to_string());
```

However, only the last assertion actually passes. `round3up("12301")` results in `12310`, `round3up("123.01")` in `123.1`, and `round3up("1.2301")` in `1.231`. If I reduce the first argument of `round_sf_with_strategy()` to 2, then the first three assertions pass, but the last one doesn't, resulting in (correct) `0.13`.

Am I misunderstanding the meaning of "significant digits" in the context of `round_sf_with_strategy()`? How would one implement consistent rounding to three significant digits?

**Comment by paupino** [comment]
You're correct in thinking something doesn't look right. I'm in transit the next couple of days but will attempt to dig into this issue this weekend to see what's going on. Will keep you posted.
