### ISSUE TITLE
Decimal::deserialize can panic

### ISSUE THREAD

**Issue by jean-airoldie** [paupino/rust-decimal#435]
The PR https://github.com/paupino/rust-decimal/pull/433 introduced a panic in the deserialize method: https://github.com/paupino/rust-decimal/blob/c74bd40701cce99b264af6b9af2e66d0f66251f1/src/decimal.rs#L710

This means that one cannot receive raw serialized decimals from a untrusted 3rd party. I'm also assuming that casting raw bytes to `Decimal`, even with the `repr(C)` freature enabled is UB.

Do you think it would be possible to make casting bytes to a `Decimal` type not UB? My specific use case is for binary serialization where serde is too slow.

**Comment by paupino** [comment]
Ha - I knew it'd come back to bite me! It's certainly possible - _ideally_ it should probably return a `Result`. What if there was a `checked_deserialize` function of some sorts to help provide this functionality? It could then become a `const` fn again I imagine.

**Comment by jean-airoldie** [comment]
> The ideal solution would be to make the decimal type work for any scale, but I'm guessing its not possible since 28 is between 2^4 and 2^5.

What I mean, is to truncate the scale when interpreting it, so that it never exceeds the maximum value, so that the `Decimal` is defined for any combination of bytes.

**Comment by jean-airoldie** [comment]
> Would something like this work for you? https://github.com/paupino/rust-decimal/compare/bug/deserialize-panic?expand=1
> 
> This allows scales < 32 to be supported and automatically rounded. With this implementation, scales >= 32 are undefined behavior. It won't panic, but it probably won't be correct. That being said, I could add some more aggressive rounding logic in there potentially to allow for scales up to ~58 (i.e. at that point in time, the number will be 0).

I think this is better than panicking. I don't think you necessarily need to support scales greater than 28 because they shouldn't occur normally. They can only occur during fuzzing or someone with malicious intent.
