### ISSUE TITLE
Feature request: Conversion from float retaining excess precision

### ISSUE THREAD

**Issue by hniksic** [paupino/rust-decimal#438]
Currently this code prints `0.1`:

```
let d = Decimal::from_f64(0.1).unwrap();
println!("{}", d);
```

At first that sounds like correct behavior and what one would want. But I would argue that it is in fact not the correct result, and that it should instead output `0.10000000000000000555111512313`.

As we know, the token `0.1` is read by Rust into an `f64` number, where it is represented by a floating-point number equal to the fraction `3602879701896397/36028797018963968`. (This ratio can be obtained in Python using `0.1 .as_integer_ratio()`, [or in Rust](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=6d3496325cbba0808235588d3996cbfc) by printing `BigRational::from_float(0.1)`.) While the resulting number can be displayed as 0.1 without loss of precision _when again re-read as float_, and while humans often think of it as 0.1, it is the fraction that is in fact used in floating-point calculations.

This is why I would expect `"0.1".parse::<Decimal>().unwrap()` to differ from `Decimal::from_f64(0.1).unwrap()`. The former reads from decimal and is precisely `0.1`, whereas the latter converts the result of the lossy conversion of the `0.1` token to floating point. The input of `Decimal::from_f64(0.1)` is the number corresponding to the above-mentioned fraction, which has an exact decimal representation (because its denominator is a power of 2): `0.1000000000000000055511151231257827021181583404541015625`. Given the constraint of a mantissa smaller than `2**96`, the closest `rust_decimal::Decimal` representation of this is `10000000000000000555111512313 * 10**-29`, so I'd expect the `Decimal` to display as `0.10000000000000000555111512313`.

The same applies to `from_f32` where `Decimal` has enough precision to hold all the digits of [13421773/134217728](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=6ee605efebfccdeb2db2edd3012ab848), and should display `0.100000001490116119384765625`.

Python's `decimal` does the equivalent conversion, except its decimal is not limited to u128, so it can accommodate the whole float:

```
>>> import decimal
>>> decimal.Decimal(0.1)
Decimal('0.1000000000000000055511151231257827021181583404541015625')
>>> decimal.Decimal("0.1")
Decimal('0.1')
```

Looking at the implementation, it's not at all obvious that the current behavior is intended. The intention seems to be to convert the number with maximum possible precision. While I'm aware that some people might consider the current behavior to be a feature, I'd still ask to change it, or at least to provide a different method for converting floats to decimals while minimizing the difference from the original number.

**Comment by hniksic** [comment]
> I think what you're asking for is really to have a function which doesn't remove this excess precision so that we ignore any float guarantees. My question I guess is: why? It'd be useful to understand the use case.

The use case is being able to closely approximate the number that `f64` works with, for various reasons: rounding, inspection, education. At least I found Python's `as_integer_ratio()` to be extremely useful in various circumstances involving transitioning from floats to exact arithmetic in order to perform well-defined rounding operations for the purposes of display. By inspection and education I mean that exact conversions between floats and rationals allows one to understand and deal with what otherwise seem like intractable phenomena like `0.1 + 0.1 + 0.1 - 0.3` evaluating to `5.551115123125783e-17`.

"Ignoring any float guarantees" sounds almost like we'd be doing something unsafe, which I believe is not the case here, unless there is reason to doubt the soundness of the algorithm Python (and `num::BigRational`) arrive at the fraction.

Having said that, I must also say that I didn't know about the guarantees you're referring to, and it's definitely interesting that .NET gives identical results. Do you think Python is just mistaken about their float->Decimal conversion? The documentation of `decimal` claims that its floating point arithmetic is "implemented in terms of published standards", including the hairy parts such as rounding and signal handiling. The [documentation](https://docs.python.org/3/library/decimal.html#quick-start-tutorial) says that "Construction from an integer or a float performs an exact conversion of the value of that integer or float", giving examples like:

```
>>> Decimal('3.14')
Decimal('3.14')
>>> Decimal(3.14)
Decimal('3.140000000000000124344978758017532527446746826171875')
```

`Decimal.from_float` [docs](https://docs.python.org/3/library/decimal.html#decimal.Decimal.from_float) make a similar point explicitly:

> Note `Decimal.from_float(0.1)` is not the same as `Decimal(‘0.1’)`. Since 0.1 is not exactly representable in binary floating point, the value is stored as the nearest representable value which is `0x1.999999999999ap-4`. That equivalent value in decimal is `0.1000000000000000055511151231257827021181583404541015625`.

I understand that Python documentation is in no way normative, I'm quoting it merely to illustrate how far they go in considering the rational number to be some form of intrinsic value of the float. I would find it puzzling that they'd miss something as basic as a fundamental guarantee afforded by IEEE 754, or that they'd recklessly flout it.

Also, does the same apply to `BigRational::from_float()` - should it return `1/10` when given `0.1f64` and `0.1f32`? I'm genuinely curious, not (only) trying to make a point. Maybe there are two different modes of float->decimal conversion, and both should be considered.

**Comment by ahrvoje** [comment]
I tend toward Python and BOOST approach, for both consistency and practical reasons.

// .NET 5
new Decimal(1.1000000000000001) == Decimal.Parse("1.1"));     // TRUE
new Decimal(1.1000000000000001) == Decimal.Parse("1.1000000000000001"));   // FALSE

**Comment by hniksic** [comment]
Thanks for working on this!

A feature is certainly better than no support for exact float conversions, but features have some issues - one that they are hard to discover and document, and the other that they don't play well with workspace builds. As I understand it, when a crate in a workspace requests a feature from a dependency, it is used for all crates in the same build. (I can dig out the exact details if you're curious.)

A pair of functions like `from_f32_exact()` and `from_f64_exact()` seem like a better choice. If you don't like expanding the API surface, perhaps make them available via a `FromFloatExact` extension trait?

**Comment by ahrvoje** [comment]
One simple real-life example, as this is not philosophical discussion, it has real-life consequences and errors.

Which of two expressions y=1 - x*x and z=(1-x) * (1+x) is more accurate at x=1 - 1e-12?

Python 3.10
```
from decimal import Decimal

x = 1 - 1e-12

y = 1 - x*x
z = (1 - x) * (1 + x)

exact_x = Decimal(x)
exact_y = 1 - exact_x*exact_x
exact_z = (1 - exact_x) * (1 + exact_x)

print(abs(y - float(exact_y)))
print(abs(z - float(exact_z)))  # this error is smaller and this is CORRECT
```

.NET 5
```
using System;
					
public class Program
{
	public static void Main()
	{
		double x = 1 - 1e-12;

		double y = 1 - x*x;
		double z = (1 - x) * (1 + x);

		System.Decimal exact_x = new Decimal(x);
		System.Decimal exact_y = 1 - exact_x*exact_x;
		System.Decimal exact_z = (1 - exact_x) * (1 + exact_x);

		Console.WriteLine("error y = {0}", Math.Abs(y - Decimal.ToDouble(exact_y)))  // this error is smaller and this is INCORRECT;
		Console.WriteLine("error z = {0}", Math.Abs(z - Decimal.ToDouble(exact_z)));
	}
}
```

Philosophy and personal preferences aside, this Decimal will not be useful for my purposes as I can not trust its results. Its that simple.
