### ISSUE TITLE
Approximate FromPrimitive f32/f64 impls

### ISSUE THREAD

**Issue by jekirl** [paupino/rust-decimal#44]
Right now FromPrimitive is implemented with the default f32/f64 behavior of rounding to an int.... I would propose that there be a lossy implementation or that it always return None -- I much prefer the former. 

In C# it is handled as follows:

> When you convert float or double to decimal, the source value is converted to decimal representation and rounded to the nearest number after the 28th decimal place if required. Depending on the value of the source value, one of the following results may occur:

> If the source value is too small to be represented as a decimal, the result becomes zero.

> If the source value is NaN (not a number), infinity, or too large to be represented as a decimal, an OverflowException is thrown.

**Comment by paupino** [comment]
Good point; I'll need to take a look into the semantics of a lossy implementation (i.e. to avoid utilizing heavy data structures like string) but it sounds reasonable. Will take a look when I get a chance and see if I can get it into the next version.
