### ISSUE TITLE
Adding a rand feature

### ISSUE THREAD

**Issue by happysalada** [paupino/rust-decimal#489]
Hi, thank you for the great library!

I'm going through generating some fake data with fake-rs for my tests. Some of my attributes are decimals.
The fake-rs number generation relies on implementing SimpleUniform from the rand crate.
I see that there is already support for fuzzers, I think ultimately the implementation would be similar.
I am happy to have a look, I was wondering though if it was something you would think worth considering ? (making sure I'm not missing something).

**Comment by paupino** [comment]
That definitely sounds like a useful idea. In my opinion, if it makes the path to using Decimal easier then it’s worthwhile considering for a feature. In this case, allowing this to be consumed by a library like ‘fake-rs’ makes a lot of sense.

**Comment by happysalada** [comment]
it looks like this can be closed now.
Thank you for answering so fast again!
