### ISSUE TITLE
error[E0658]: arbitrary expressions in key-value attributes are unstable

### ISSUE THREAD

**Issue by uglyoldbob** [paupino/rust-decimal#491]
I'm compiling a rust project that gets hung up on the rust_decimal package with the error 

> error[E0658]: arbitrary expressions in key-value attributes are unstable

It points to like 13 of src/arithmetic_impls.rs in this package.
What can i do to resolve this? It started right after my last "cargo update" command I ran.

**Comment by paupino** [comment]
Hi @uglyoldbob,
What version of the rust compiler are you using? We’re leveraging some macro features in there which require a minimum version of 1.54 or greater. Is it possible that you’re running a version before this?

**Comment by uglyoldbob** [comment]
I was wondering if that might be the case. I'm using rustc 1.53. Gotta update my system and try later.

**Comment by uglyoldbob** [comment]
I updated and tried with rust 1.57 and it works now
