### ISSUE TITLE
Trait to convert from a Decimal

### ISSUE THREAD

**Issue by turion** [paupino/rust-decimal#492]
It would be really helpful if there was a trait like

```rust
trait FromDecimal<T> {
    fn from_decimal(x: Decimal) -> Option<T>
}
```

Alternatively, it would be great if `TryInto` was implemented for all the primitive types.

I'm aware of `ToPrimitive` and `FromPrimitive`, but it doesn't suit my needs because it is not polymorphic in the output type.

I can submit a PR if you are interested.

**Comment by paupino** [comment]
I like the idea of implementing `TryInto`/`TryFrom` for each of the primitive types as opposed to a new trait, namely as it'd be easier to discover. I believe these implementations only exist for `f32`/`f64` at the moment, however it shouldn't be too tricky to expand this for other primitives. That being said, for implementing this it should likely follow the same lines as `impl_from!` (i.e. could require some refactoring of `f32` and `f64` to follow this too).

Very much open to a PR if you're willing to take a stab at it!

**Comment by turion** [comment]
Ok, I opened https://github.com/paupino/rust-decimal/pull/493 and I'm open to your comments :)
