### ISSUE TITLE
Latest version does not compile when the `std` feature is disabled

### ISSUE THREAD

**Issue by Jules-Bertholet** [paupino/rust-decimal#500]
Offending commit: 168fa67932b88bf65d5fa6c84612f02f052e6ec5

The `TryFrom` impls use `to_string`, from the [`ToString` trait](https://doc.rust-lang.org/stable/std/string/trait.ToString.html) from the prelude. This trait isn't available when `std` is disabled.

**Comment by paupino** [comment]
That's no good. I'll also need to see why tests failed to detect this. I'll get a fix out shortly.

**Comment by paupino** [comment]
This should be working again now. Sorry for the disruption!

I'll take a look into how we can test `no_std` better to hopefully capture this before merge.
