### ISSUE TITLE
Add a Changelog 

### ISSUE THREAD

**Issue by brianheylin-ds** [paupino/rust-decimal#507]
Can you please add a changelog, it makes reviewing changes between versions a lot easier.

https://keepachangelog.com/en/1.0.0/

Thanks

**Comment by paupino** [comment]
We do have a changelog, unfortunately called `VERSION.md` at present. Wouldn’t be too difficult to change this for consistency.

**Comment by paupino** [comment]
I've renamed `VERSION.md` to `CHANGELOG.md` which will land in #518 however work still needs to be done to follow the accepted format. I'll see what we can do to make this happen going forward.

**Comment by brianheylin-ds** [comment]
Great thanks @paupino
