### ISSUE TITLE
Panic when using `i64::MIN` and `.round_dp`

### ISSUE THREAD

**Issue by lukesneeringer** [paupino/rust-decimal#508]
The following code panics with a cryptic error message:

```rs
Decimal::new(i64::MIN, 9).round_dp(3)
```

The error message is "attempt to negate with overflow". Incidentally, it seems to only happen on debug, not release.
This seems odd to me though, as it's still fewer than 96 bits.

**Comment by paupino** [comment]
I've tried to [reproduce](https://github.com/paupino/rust-decimal/compare/issue/508?expand=1) this however I can't seem to get it to crash (e.g. both debug/release). A couple of questions:
* Is the code snippet in question complete? Does the test I wrote work for you?
* What version of the library are you using? What feature flags have you got configured?

Looking back, there was a bug in overflow however it was also in an [early version](https://github.com/paupino/rust-decimal/pull/185) of the library.

**Comment by lukesneeringer** [comment]
Huh, weird, I must have been getting tired when debugging on Friday. I concur that what I gave you works fine. I still have the problem in my wider code, I will work to distill it down and get you a proper reproduction case (or else I will close this).

**Comment by lukesneeringer** [comment]
I found the problem, and it's in my code. I was actually doing...

```rs
let value = i64::MIN;
Decimal::new(value).round_dp(if value.abs < 1_000_000_000 { 4 } else { 3 })
```

...and the `value.abs()` is what's at fault, because `i64::MIN.abs()` overflows. I oversimplied the test case too much when reporting or you'd've likely identified it immediately.

Sorry for the trouble!
