### ISSUE TITLE
Possibly malicious package "rustdecimal"

### ISSUE THREAD

**Issue by safinaskar** [paupino/rust-decimal#514]
Hi. I found this package: https://docs.rs/rustdecimal/latest/rustdecimal/ . It seems this is clone of your package created for malicious purposes

**Comment by c410-f3r** [comment]
Woowwwwwwww....

Fake: https://crates.io/api/v1/crates/rustdecimal/1.23.1/download ~110.7k
Real: https://crates.io/api/v1/crates/rust_decimal/1.23.1/download ~113.2k

Definitely a legit malicious package that can be easily downloaded

**Comment by c410-f3r** [comment]
I personally have no idea what has to be done in a situation like this. Pinging the members of the `crates.io` team for awareness (Hope you guys don't mind)

@jtgeibel
@Turbo87
@carols10cents
@JohnTitor
@locks
@pichfl
@smarnach

**Comment by paupino** [comment]
Definitely created for malicious purposes. It looks like the versions previously to "latest" contain some [malicious code](https://docs.rs/rustdecimal/1.23.4/src/rustdecimal/decimal.rs.html). They've ripped it out in `1.23.5`, but have the "use" statements and library dependencies remaining.

I'm not sure what to do in this situation either so thank you both for raising awareness and for tagging the crates team. Hopefully we can get the malicous version completely yanked.

**Comment by jtgeibel** [comment]
I assume the malicious code is related to the curl Easy with obfuscated urls, correct? (I'm on mobile currently so can't really analyze further at the moment.)

**Comment by paupino** [comment]
@jtgeibel Yep, correct. In essence, it looks like it's downloading a binary masked as a "readme" file and then depending on the OS, making it executable and running it.

**Comment by jtgeibel** [comment]
We've locked the account, deleted the crate from the database, and have an update to the index pending review. To clarify, it looks like there are <500 total downloads and no reverse dependencies, so hopefully only bots have downloaded this version.

**Comment by paupino** [comment]
@jtgeibel Thank you for the quick response!

**Comment by c410-f3r** [comment]
Thanks @safinaskar for reporting the problem and @jtgeibel for fixing everything

Now I wonder if `rustdecimal` can be taken by another person or if similar names like `rust-decimal` can be used again for malicious purposes

**Comment by carols10cents** [comment]
In the future, emailing help@crates.io or security@rust-lang.org is the best way to get in contact with the right folks. Thanks!

**Comment by pietroalbini** [comment]
Hey, Pietro from the Rust Security Response WG!

Thank you all for bringing this to our attention, [we just published an advisory](https://blog.rust-lang.org/2022/05/10/malicious-crate-rustdecimal.html). Last week we also notified GitLab's security team and reported the attacker to both their registrar and hosting provider. In the future please make sure to report similar problems [according to Rust's security policy](https://www.rust-lang.org/policies/security), as that's the fastest way to get this to our attention :slightly_smiling_face:

**Comment by juanandresgs** [comment]
Is anyone willing to provide a copy of the malicious crate? Would also love to know about any infrastructure it was contacting for a next-stage payload.

**Comment by carols10cents** [comment]
@juanandresgs I have the crate files, please contact me via email - carol dot nichols at gmail - and I will send them to you.

**Comment by kurtseifried** [comment]
issued GSD-2022-1002520 https://raw.globalsecuritydatabase.org/GSD-2022-1002520 since it will probably never get a CVE ID.

**Comment by carols10cents** [comment]
Thank you @kurtseifried ! I love the Open Source Security podcast :)
