### ISSUE TITLE
Clean up feature dependencies to use optional syntax where necessary

### ISSUE THREAD

**Issue by paupino** [paupino/rust-decimal#521]
Requires Rust `1.60`.

As per: https://doc.rust-lang.org/cargo/reference/features.html#dependency-features

We can move some of the `std` features into `std` only enabling it when the feature is defined.

**Comment by c410-f3r** [comment]
This pre-1.60 behaviour of polling additional dependencies when optional features are used was a technical debt of Cargo so I will gladly work on this issue once the minimal compiler version reaches 1.60.

**Comment by paupino** [comment]
Addressed in #551. Further work needs to be done to clean up towards `dep:` syntax
