### ISSUE TITLE
`Decimal` probably shouldn't implement `From<u128/i128>`

### ISSUE THREAD

**Issue by c410-f3r** [paupino/rust-decimal#545]
Because `Decimal::from((u128|i128)::MAX)` panics at runtime. As such, `TryFrom` looks like the only reasonable approach.

https://doc.rust-lang.org/std/convert/trait.From.html
> Note: This trait must not fail. The From trait is intended for perfect conversions. If the conversion can fail or is not perfect, use [TryFrom](https://doc.rust-lang.org/std/convert/trait.TryFrom.html).

**Comment by paupino** [comment]
Agreed. I think it's time to start a `v2` branch to start work towards cleaning up the API / Errors etc.

**Comment by c410-f3r** [comment]
I am house-keeping my dashboard closing issues that will probably take time to resolve.

@paupino If it is of your interest, adding another item on #354 might be a good replacement.
