### ISSUE TITLE
Error trying to convert a string float from a response field.

### ISSUE THREAD

**Issue by deloused** [paupino/rust-decimal#549]
I am trying to deserialize response data into the following, how do I use this library with serde. Serde is private

```
#[serde_as]
#[derive(Debug, Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct Data {
    //input is "100.4455"
    #[serde(with = "rust_decimal::serde::str")]
    pub value: Decimal,
}
```

```
error[E0432]: unresolved import `rust_decimal::serde::str`
use rust_decimal::serde::str;
**"^^^^^^^^^^^^^^^^^^^^^^^^ no `str` in `serde`"**
```

```
error[E0603]: module `serde` is private
#[serde(with = "rust_decimal::serde::str")]
**^^^^^^^^^^^^^^^^^^^^^^^^^^ not found in `rust_decimal::serde`**
```

**Comment by paupino** [comment]
Have you enabled the `serde-with-str` feature? https://github.com/paupino/rust-decimal#serde-with-str

This will make the `serde` module public and allow you to reference `str` accordingly.

I'm pretty sure this is the issue, however if not can you specify you `Cargo.toml` entry for `rust_decimal`?

**Comment by deloused** [comment]
Yep, thats it. Cheers Paupino
