### ISSUE TITLE
 serde-with-str - str_option does not work with bincode, unlike serde-str #483 

### ISSUE THREAD

**Issue by ev94** [paupino/rust-decimal#563]
Hi,
I have the same issue as  #483  but with `Option<Decimal>`

```
#[derive(Debug, serde::Deserialize, serde::Serialize)]
struct Foo {
    #[serde(with = "rust_decimal::serde::str_option")]
    dec: Option<rust_decimal::Decimal>,
}
```
This doesn't work. If I use the feature serde-str, it works.

I'm using rust_decimal v1.27.0 and bincode v1.3.3

Thx

**Comment by paupino** [comment]
I've believe I've created a fix for this - once this is merged, would you like to test it on `master` to see if it resolves your issue? If so, I can look at doing a minor version release so you can leverage the fix formally.
