### ISSUE TITLE
Feature request: `Decimal::is_integer()`

### ISSUE THREAD

**Issue by finnbear** [paupino/rust-decimal#590]
I recently integrated `rust_decimal::Decimal` into a large codebase and found that most of the API was intuitive and more complete than that of `bigdecimal::BigDecimal`. One thing I missed is the [`.is_integer()` function](https://docs.rs/bigdecimal/latest/bigdecimal/struct.BigDecimal.html#method.is_integer). I (and the internals of this crate) end up writing `.scale() == 0` everywhere, which is far less intuitive (and possible less correct given the possibility of non-normalized decimals?) than `.is_integer()`.

**Comment by schungx** [comment]
`.scale() == 0` misses the cases where `.scale() > 0` but the raw number itself has zeros at the end.  Such as: `1000, scale=3` is equivalent to `1, scale=0`.

**Comment by finnbear** [comment]
> `.scale() == 0` misses the cases where `.scale() > 0` but the raw number itself has zeros at the end. Such as: `1000, scale=3` is equivalent to `1, scale=0`.

Thanks, that's what I was worried about when I said `scale() == 0` might be *possibly* less correct. I think that's another reason to add a (correct) `is_integer` function.

**Comment by paupino** [comment]
Fortunately, it's a fairly easy function to implement so I've put something together in the attached PR. 

> I (and the internals of this crate) end up writing .scale() == 0 everywhere

Rest assured, we don't use scale to identify an integer like this within the crate. When we check for scale being zero we're actually intending to check that the mantissa is a whole number without any "manipulation" required (e.g., we may want to transform `1.000` into `1`).
