### ISSUE TITLE
`trunc_with_scale` issue

### ISSUE THREAD

**Issue by moderncodes** [paupino/rust-decimal#599]
rustc 1.71.0
rust_decimal = "1.30.0"
rust_decimal_macros = "1.30.0"

Bellow code example, **trc_4** result value from [trunc_with_scale](https://docs.rs/rust_decimal/1.30.0/rust_decimal/struct.Decimal.html#method.trunc_with_scale) does not truncate to defined scale.
```Rust
use rust_decimal::prelude::*;
use rust_decimal_macros::dec;

fn main() {
    let val_1 = dec!(999.25);
    let val_2 = dec!(1938.03);
    let div_3 = val_1 / val_2;
    let trc_4 = res_3.trunc_with_scale(7); 
    
    println!("val_1: {:?}; val_2: {:?}; div_3 : {:?}; trc_4: {:?}" ,val_1, val_2, div_3, trc_4);
}
```
**Output**
```
val_1: 999.25; val_2: 1938.03; div_3: 0.5156008936910161349411515818; trc_4: 0.5
```
**Expected**
```
val_1: 999.25; val_2: 1938.03; div_3: 0.5156008936910161349411515818; trc_4: 0.5156008
```

**Comment by paupino** [comment]
Thank you for raising this. It appears the algorithm was implicitly rounding when requiring multiple words. Fortunately this is an easy fix - PR incoming.

**Comment by moderncodes** [comment]
Would you please update crates.io, to include this fix, or you follow some process?

**Comment by paupino** [comment]
Will get a release out today. I was looking at trying to get another feature in there, however haven't found the time. Publishing a small release isn't necessarily a bad thing!

**Comment by moderncodes** [comment]
Thank you!
