### ISSUE TITLE
`is_integer` has BUG

### ISSUE THREAD

**Issue by gaoqiangz** [paupino/rust-decimal#604]
```rs
assert!(rust_decimal::Decimal::from_str("0.4000000000000000000").unwrap().is_integer()); //will panic
```

**Comment by paupino** [comment]
I don't think this will panic right now as is, however I think it _should_ panic. As an alternative example:

```rust
let number = dec!(0.4000000000000000000);
println!("Number: {number}");
println!("Is Integer? {}", number.is_integer());
```

This will output:
```
Number: 0.4000000000000000000
Is Integer? true
```

This is incorrect: the `is_integer` function should be returning `false`. 

It should be a trivial fix - it is likely a rounding issue. To note: `dec!(0.400_000_000)` is correct however `dec!(0.4_000_000_000)` will fail.
