### ISSUE TITLE
How to serialize Decimal and still keep the results in order (bitwise comparison)

### ISSUE THREAD

**Issue by KKould** [paupino/rust-decimal#610]
I will store Decimal as a Key in RocksDB, but how can I keep Decimal in order after serialization and arrange Decimal in a more reasonable manner?

**Comment by paupino** [comment]
Hi @KKould,

I'm not sure I quite understand the question here - but admittedly, I'm unfamiliar with RocksDB. If this is about key clustering, this may be more suitable to ask on the RocksDB project.

That said - I'll try to provide a couple of answers:
* Rust Decimal has a `c-repr` feature if you wanted to align structure across 128 bits consistently. This would allow you to perform memory translation if needed.
* There is a [`serialize`](https://docs.rs/rust_decimal/latest/rust_decimal/struct.Decimal.html#method.serialize) function to consistently serialize into a collection of bytes. This is in a well-defined order. 
* You could also use something like [`Borsh`](https://github.com/paupino/rust-decimal#borsh) to perform binary serialization.

I'm not sure if this helps at all. If not, if you could please provide some further context it may help direct me a bit more.

**Comment by KKould** [comment]
Implement Memory Comparable: After serialization, it can still be sorted (same order as before serialization)
e.g. TIDB: https://github.com/pingcap/tidb/blob/48f6b35d442289721af6fd5753b4b9c151e1d384/util/codec/decimal.go#L25C22-L25C22

**Comment by KKould** [comment]
Implement Memory Comparable: After serialization, it can still be sorted (same order as before serialization)
e.g. TIDB: https://github.com/pingcap/tidb/blob/48f6b35d442289721af6fd5753b4b9c151e1d384/util/codec/decimal.go#L25C22-L25C22

**Comment by paupino** [comment]
Another thing you could try is to implement this manually. For example:

* Retrieve the [mantissa](https://docs.rs/rust_decimal/latest/rust_decimal/struct.Decimal.html#method.mantissa) as well as the [scale](https://docs.rs/rust_decimal/latest/rust_decimal/struct.Decimal.html#method.scale)
* Or retrieve [unpacked decimal](https://docs.rs/rust_decimal/latest/rust_decimal/struct.Decimal.html#method.unpack)

Then recombine them for your requirements. The code you've linked seems to write precision, scale then mantissa. You could emulate this by calculating the precision (i.e. length of the mantissa), followed by scale, followed by mantissa. Perhaps that would do the trick?

i.e. in pseudo like code

```rust
let mantissa = number.mantissa();
let scale = number.scale();
let precision = mantissa.ilog10() + 1;
// This is not space efficient
let mut bytes = Vec::new();
bytes.extend(precision.to_be_bytes());
bytes.extend(scale.to_be_bytes());
bytes.extend(mantissa.to_be_bytes());
```
