### ISSUE TITLE
rust_decimal_macros 1.35.0 not on crates.io (Or: Error in Documentation)

### ISSUE THREAD

**Issue by the-kenny** [paupino/rust-decimal#660]
Newest version of `rust_decimal_macros` on crates.io is `1.34.2`, but the documentation explicitly uses `1.35`. 

As `rust_decimal_macros-1.34.2` seems to work fine with `rust_decimal-1.35.0` I see two solutions:

- Release `rust_decimal_macros-1.35.0` to sync versions
- Fix documentation to use `rust_decimal_macros = "1.35"` in `[dependencies]`

**Comment by paupino** [comment]
Oof, sorry about that. Since `1.34.2` == `1.35.0` (code speaking) I didn't release it, however the release scripts auto update the readme docs to be consistent.

Rather than fix the documentation, I'm going to publish 1.35.0 of macros - I have a fix building which I'll merge/publish shortly.

**Comment by paupino** [comment]
This has now been published: https://crates.io/crates/rust_decimal_macros/1.35.0
