### ISSUE TITLE
Expose `MAX_PRECISION` constant

### ISSUE THREAD

**Issue by PgBiel** [paupino/rust-decimal#684]
Hey!

I've noticed the docs mention `Decimal::MAX_PRECISION`:

https://github.com/paupino/rust-decimal/blob/fa8857946cfb3bc4a08244b60133082d8dc575e7/src/decimal.rs#L873

However, this constant isn't currently exposed, and it is useful as it determines whether or not certain operations, such as `set_scale`, can error.

Could this constant be exposed? (And perhaps any other missing essential constants from the `constants` module?)

Thanks!

**Comment by PgBiel** [comment]
Ah, of course, that's true; checking for the error itself is probably ideal. My example was a bit contrived, but I was thinking that you could use this information to elide certain operations. In my particular case, I've implemented an abstraction over decimal rounding with some extras, and the abstraction is a no-op when rounding beyond the max precision, so a little "if" would be a nice little optimization (and/or help ensure or even assert correctness). So I think it has its use cases! 🙂

**Comment by Tony-Samuels** [comment]
> The downside of this approach however is that the maximum number of significant digits that can be represented is roughly 28 base-10 digits (29 in some cases).

https://docs.rs/rust_decimal/latest/rust_decimal/#comparison-to-other-decimal-implementations

A concern I have with exposing the `MAX_PRECISION` constant is potential misuse and misunderstanding. Despite its name, it's not actually the maximum number of base-10 digits that can be stored, just a limit on how high the `scale` factor can go.

However, I think it would be fine to expose it under the name `MAX_SCALE` or something similar, which I believe would still suit your purposes? If so, I'll raise an MR and see if anyone else agrees with me.

**Comment by PgBiel** [comment]
Good point! Sounds good to me, and this information could be exposed as a doc comment on the constant.
