### ISSUE TITLE
Is there a method for this?

### ISSUE THREAD

**Issue by frederikhors** [paupino/rust-decimal#689]
Thank you all for this amazing crate!

Is there a method like `normalize()` that return at least two decimals?

For example: `decimal_number.normalize(2)`, such as:

- `123.12300` -> `123.123`

- `123.00` -> `123.00`

- `123` -> `123`

- `123.0001200` -> `123.00012`

**Comment by Tony-Samuels** [comment]
I believe you're looking for [Decimal::rescale](https://docs.rs/rust_decimal/latest/rust_decimal/struct.Decimal.html#method.rescale). Take a look at the docs and see if it behaves the way you're hoping for.

**Comment by Tony-Samuels** [comment]
I think what you want will be some combination of rescaling and `normalize`. If you `normalize` first, that will strip the `0`s. You should then be able to re-add them. Probably by doing something like:
```rust
let normalized = input.normalize();
let rescaled = normalized.rescale(std::cmp::max(normalized.scale(), 2));
rescaled
```
```
