### ISSUE TITLE
Replace ToDecimal with Into and From?

### ISSUE THREAD

**Issue by JP-Ellis** [paupino/rust-decimal#8]
I was having a quick look through your code, and I see you have a new trait called `ToDecimal` which simply converts integer types into a decimal.  I was curious as to why you didn't opt for the [`Into`](https://doc.rust-lang.org/std/convert/trait.Into.html) and [`From`](https://doc.rust-lang.org/std/convert/trait.From.html) traits from the standard library which do exactly that?

Would you like a pull request to remove the `ToDecimal` trait and replace it with the standard library equivalent?

**Comment by paupino** [comment]
Short answer; no, there is no good reason for this and it should be updated to use Into and From. If you'd like to help contribute then I'd certainly be most grateful! Nevertheless, thank you for raising the issue - it's been a todo item for a while now.
