### ISSUE TITLE
Implement `checked` operator functions

### ISSUE THREAD

**Issue by paupino** [paupino/rust-decimal#80]
To help alleviate some of the panic scenario's currently present in the library we should introduce `checked` methods. Checked returns an `Option<Decimal>` and returns `None` on overflow.

**Comment by 0e4ef622** [comment]
Is anyone working on this? If not, I'd be willing to since I'm going to need it for a project.

**Comment by paupino** [comment]
Not yet - please feel free to pick it up @0e4ef622!
