### ISSUE TITLE
Rescaling can overflow a number during standard operations

### ISSUE THREAD

**Issue by paupino** [paupino/rust-decimal#89]
Currently, rescaling can cause a silent overflow during some common operations which leads to incorrect results. A good test case as raised by @rkusa is:

```
---- it_adds_decimals stdout ----
	thread 'it_adds_decimals' panicked at 'assertion failed: `(left == right)`
  left: `"12.45378151260504201681"`,
 right: `"4.5309652611786082574523276562"`: 11.815126050420168067226890757 + 0.6386554621848739495798319328', tests/decimal_tests.rs:168:8
```

In this particular case, `11.815126050420168067226890757` (scale 27) is being rescaled to a representation of 28. This causes an expected overflow logically however because the overflow is consequently ignored it leads to incorrect results. Behind the scene's it currently loses the significance and converts `11.815126050420168067226890757` to `3.8923097989937343078724957234`. Consequently, `0.6386554621848739495798319328` + `3.8923097989937343078724957234` = `4.5309652611786082574523276562`.

In order to resolve this; the rescale logic should be refactored and instead return an extra 32 bit's for overflow, which is ultimately used in any resulting calculations (as required).

**Comment by paupino** [comment]
I've taken a further look and am going to change approach slightly. Returning the overflowing bit is relatively easy however there is not much that can be done with it. I think a much more gracious solution is to round the number upon rescaling - namely because it can't be represented in greater detail. In the example above, `0.6386554621848739495798319328` should be scaled _down_ to `0.638655462184873949579831933` since the alternative can't be scaled up without overflowing giving a final result of `12.453781512605042016806722690`. This seems consistent with other libraries.

**Comment by rkusa** [comment]
> I think a much more gracious solution is to round the number upon rescaling - namely because it can't be represented in greater detail. In the example above, 0.6386554621848739495798319328 should be scaled down to 0.638655462184873949579831933 since the alternative can't be scaled up without overflowing giving a final result of 12.453781512605042016806722690.

Sounds good! Thanks @paupino for having a look and also for providing details and reasoning 👍

**Comment by rkusa** [comment]
Out of curiosity, for a consistent behavior, you could round to the max possible precision in the multiplication case as well, instead of giving a `panic`?

https://github.com/paupino/rust-decimal/blob/7a3728a5efd3c4fcdacb50578b71a0478165e35f/src/decimal.rs#L1811-L1817

(I've already encountered this panic multiple times)

**Comment by paupino** [comment]
Yes; good catch. Let’s open a new ticket for this case and I’ll see if I can get to it today - I believe the fix should be relatively straight forward. If possible, can you provide some failure cases for this?

**Comment by paupino** [comment]
Issue created for the multiplication case at #96.
