### ISSUE TITLE
Multiplication underflow should be rounded instead of panicing

### ISSUE THREAD

**Issue by paupino** [paupino/rust-decimal#96]
Currently, multiplication can underflow in certain situations from the following lines:

https://github.com/paupino/rust-decimal/blob/7a3728a5efd3c4fcdacb50578b71a0478165e35f/src/decimal.rs#L1809-L1817

For consistency, we should attempt to round on underflow situations whilst applying checked functions for overflow.

**Comment by paupino** [comment]
Easiest way to reproduce this is with two highly significant numbers multiplying together. 
e.g.
`2.1234567890123456789012345678 * 2.1234567890123456789012345678` currently panics whereby I'd expect a rounded result of `4.5090687348026215523554336227`.

**Comment by rkusa** [comment]
Here is an example. The numbers from #89 could be re-used:  `0.6386554621848739495798319328` * `11.815126050420168067226890757` will throw `Multiplication underflowed`.

I've created a smaller example to show how we could end up with such numbers. While I purposely build this example to panic, I sometimes encounter this panic after long sequences of "real" operations.

```rust
let rate = Decimal::new(19, 2);
let part = rate / (rate + Decimal::new(1, 0));

let a = Decimal::new(74, 0) * part; // = 11.815126050420168067226890757
let b = Decimal::new(4, 0) * part; // = 0.6386554621848739495798319328
let result = b * a; // thread 'main' panicked at 'Multiplication underflowed: 35 > 28'
```

Thanks!

**Comment by paupino** [comment]
Cool; I'll add that test case too. Result here should round to approx `7.5457947885036367488171739292`
